### ISSUE TITLE
panic 后是否应该 Retry

### ISSUE THREAD

**Issue by 0xDkd** [jiajunhuang/gotasks#1]
如题所示，假设演示代码中
```go
handler2 := func(args gotasks.ArgsMap) (gotasks.ArgsMap, error) {
		time.Sleep(time.Duration(1) * time.Second)
                panic("test")
		return args, nil
	}
```
加入异步队列之后，会发生 panic，但是 Retry 的机制是判断有没有 err 出现，当出现 panic 的时候只能进行 recover 相关的处理，recover 相关处理并没有 Retry。

请问正常情况下是否需要 Retry 呢？还是只保留相应的 stuck 信息即可

**Comment by jiajunhuang** [comment]
这个其实和业务需求强相关。有些任务是即使失败了也不能重试的，有些是应当重试的。
