### ISSUE TITLE
Any documents?

### ISSUE THREAD

**Issue by dingweihua** [jiajunhuang/gotasks#5]
Is there any document on this project?

I'm a totally beginner on Go task queue. It's not that easy to understand the demo example.
So do you plan to add any document to help us have a better understanding of the codes?

Thanks

**Comment by jiajunhuang** [comment]
I'm sorry about that, I'll improve the documents as soon as I can.

**Comment by dingweihua** [comment]
Thanks! @jiajunhuang

**Comment by jiajunhuang** [comment]
I've update the demo for both producer and consume in the `README.md` file, have a look for it, let me know if you have other questions :)
