### ISSUE TITLE
Support the worker w/o registering handlers first?

### ISSUE THREAD

**Issue by dingweihua** [jiajunhuang/gotasks#7]
In the examples/consumer/main.go, we need to register the handlers first [L29](https://github.com/jiajunhuang/gotasks/blob/master/examples/consumer/main.go#L29). 
Then the producer is able to enqueue one of the registered jobs (corresponding to the handlers).

Is it possible that we don't need to register handlers first? Just like Python RQ, the worker can handle any enqueued jobs which could be any functions [L413](https://github.com/rq/rq/blob/master/rq/queue.py#L413). Based on this, the producer and consumer could be totally uncoupled.

Thanks!

**Comment by jiajunhuang** [comment]
No. It's too complex for Go to support such a feature, and it'll be not compatible if name of handler function changed.

**Comment by dingweihua** [comment]
Sorry, I don't understand why it couldn't be implemented by Go.

Actually the handler function exists in the same package as the worker. The worker can only receive the function name and args from the queue, and then instantiates a handler with the function name and args to run it. You mean it's difficult to instantiate a function with name in Go?
If name changed, exception would be raised on "no related handler function found".

Please leave more comments if i missed something. Thanks!

**Comment by jiajunhuang** [comment]
You can have a try, it'll bring lots of reflect code in it, it's complex and hard to maintain.
